version: '3.8'

services:
  postgres-tech:
    image: postgres:16
    container_name: pg-tech
    environment:
      POSTGRES_USER: pg-user
      POSTGRES_PASSWORD: pg-pwd
      POSTGRES_DB: tech
    ports:
      - "5429:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: