apiVersion: batch/v1
kind: Job
metadata:
  name: equipment-sets-populator-job
  namespace: prodms
spec:
  template:
    spec:
      containers:
        - name: curl-container
          image: richardjkendall/curl-bash:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              equipmentSets=(
                '{"number": "EQS.085.26.001", "name": "Набор для шлифовки", "description": "Некоторое описание"}'
                '{"number": "EQS.085.26.001", "name": "Набор для шлифовки", "description": "Некоторое описание"}'
                '{"number": "EQS.085.32.005", "name": "Набор для фрезеровки", "description": "Некоторое описание"}'
                '{"number": "EQS.085.40.001", "name": "Набор для токарной обработки", "description": "Некоторое описание"}'
                '{"number": "EQS.085.40.002", "name": "Набор для токарной обработки", "description": "Некоторое описание"}'
                '{"number": "EQS.085.40.003", "name": "Набор для токарной обработки", "description": "Некоторое описание"}'
              )

              
              
              url=http://tech-svc.prodms.svc:8080/api/v1/equipment-sets
              
              for body in "${equipmentSets[@]}"; do
                echo "Sending request with body: $body"
                curl -X POST ${url} \
                  -H "Content-Type: application/json" \
                  -d "$body"
                echo ""
              done
      restartPolicy: Never