apiVersion: batch/v1
kind: Job
metadata:
  name: blanks-populator-job
  namespace: prodms
spec:
  template:
    spec:
      containers:
        - name: curl-container
          image: richardjkendall/curl-bash:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              blanksSets=(
                '{"number": "BL.100.40.13", "material": "Steel 40X", "params":  "{\"name\": \"test-name\", \"age\": 17}"}'
                '{"number": "BL.100.40.12", "material": "Steel 40X", "params":  "{\"name\": \"test-name\", \"age\": 27}"}'
                '{"number": "BL.100.41.13", "material": "Steel 45", "params":  "{\"name\": \"tesdt-name\", \"age\": 18}"}'
                '{"number": "BLB.101.40.13", "material": "Steel 20X", "params":  "{\"name\": \"fara\", \"age\": 19}"}'
                '{"number": "BLR.102.40.13", "material": "Steel 20X", "params":  "{\"name\": \"tesame\", \"age\": 17}"}'
                '{"number": "BL.100.45.12", "material": "Steel 35", "params":  "{\"name\": \"test-name2\", \"age\": 12}"}'
                '{"number": "BL.100.49.12", "material": "Steel 35", "params":  "{\"name\": \"test-name22\", \"age\": 27}"}'
                '{"number": "BL.100.44.13", "material": "Steel 35", "params":  "{\"name\": \"tesdt-name\", \"age\": 18}"}'
                '{"number": "BLB.101.33.13", "material": "Steel 20X", "params":  "{\"name\": \"fara\", \"age\": 19}"}'
                '{"number": "BLR.102.33.13", "material": "Steel 20X", "params":  "{\"name\": \"tesame\", \"age\": 17}"}'
              )
              
              
              
              url=http://tech-svc.prodms.svc:8080/api/v1/blanks
              
              for body in "${blanksSets[@]}"; do
                echo "Sending request with body: $body"
                curl -X POST ${url} \
                  -H "Content-Type: application/json" \
                  -d "$body"
                echo ""
              done
      restartPolicy: Never
